# Generated by Django 5.1.1 on 2024-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_client_delete_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='client',
            name='term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AddField(
            model_name='client',
            name='time_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица времени'),
        ),
    ]
